server:
  port: 8081
spring:
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:postgresql://ec2-34-247-249-224.eu-west-1.compute.amazonaws.com:5432/d8gsjss66jiqun
    # url: jdbc:postgresql://servachok2021.ddns.net:35432/postgres
    username: kvfgmyfcwkdbxv
    password: 1accb488fcaffc96c420ac4e80c744591235c62a1f8de1ee68d673c8077b4840
  jpa:
    open-in-view: on
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:db/migration/v1/changelog.yaml
