server:
  port: 8081
spring:
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:postgresql://servachok2021.ddns.net:35432/postgres
    username: postgres
    password: password
  jpa:
    open-in-view: on
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:db/migration/v1/changelog.yaml
